### ISSUE TITLE
Caching of blank pages

### ISSUE THREAD

**Issue by sewingparts** [SewingPartsOnline/expert-pancake#1]
We are having issues with Categories being cached with no content.  The clear cache from the update button on each category works fine to clear it.  The update button from the Page template does not clear the cache, nor does the Global Clear Scheduled Task

**Comment by nelsonlaquet** [comment]
This issue is resolved. The problem was that the logic that detected search engines was dumb and did the wrong thing. It resulted in blank pages being cached if a search engine got to one of the category pages before we did.

Search engines now see the (uncached) paginated results.
